# CentOS 7 + IBM Installation Manager
# Original Author Andre Fernandes - https://github.com/andrefernandes/docker-websphere

FROM centos:centos7

MAINTAINER John Jacobson - jjacobso@gmail.com

ADD installim.sh /opt/installim.sh

RUN /opt/installim.sh

#CMD ["/opt/IBM/InstallationManager/eclipse/tools/imcl","-c"]

